# Site settings

title: Y4iT Pro

baseurl: http://toffmendoza.me/sandbox-y4it-pro
#baseurl: https://pro.y4it.org/

baseurlDisplay: "pro.y4it.org"

# Build settings
markdown: kramdown
permalink: pretty

# Site variables
switchCountdown: false
switchAnnouncement: false
switchSpeakers: true
switchSpeakersDescription: false
switchSchedule: false
#switchScheduleOrder: "alphabetical"
switchRegistration: true
switchBadges: false
switchHowToReg: false
switchPayment: false
switchFAQ: false
switchPartners: true
switchTerms: false

switchSponsor: false

urlRegister: "https://sitf.typeform.com/to/hzW46Y"
urlAppendRegister: "/register"

urlRegisterShorter: "http://bit.ly/y4itproregister"
urlRegisterShorterDisplay: "bit.ly/y4itproregister"

#urlAppendRegister: "/register"
#urlAppendSponsorship: "/sponsor"
#urlAppendSponsorshipPackages: "/files/Y4iT2017SponsorshipPackages.pdf"

urlOfficial: "https://pro.y4it.org/"
urlFacebook: "https://www.facebook.com/ilove.Y4iT/"
urlTwitter: "https://twitter.com/y4it"
urlInstagram: "https://www.instagram.com/y4it/"
urlYouTube: "https://www.youtube.com/user/iloveY4iT"
urlSnapchat: "https://www.snapchat.com/add/y4it"
urlViber: "http://chats.viber.com/y4it"

urlY4iT: "https://y4it.org/"

#urlReg: http://pro.y4it.org/register/

#urlAppendPackage: "/sponsorship-package.pdf"
#urlAppendDeck: "/sponsorship-deck.pdf"
##urlPartnerConfirmation: "http://y4it.org/isupporty4it"

##urlCert: http://pro.y4it.org/certificates

dataSpeakers:
 - id: "icanasa"
   pre: "Mr."
   name: "Israel Dacanay Canasa"
   affiliation:
    - designation: "Developer"
      company: "Timble CVBA, WIZMEDIA"
   description:
    - "Ra'el is a programmer by profession, creative by heart, and a tech-entrepreneur by soul. He leads a web development and design company named WIZMEDIA (wizmedia.net). He founded a startup company named Creatizens (creatizens.com) which connects elite creative type Freelancers with awesome clients. He currently works with Timble CVBA, a Web Development Company based in Belgium."
   image: "coll_web-speaker-icanasa.jpg"
 - id: "ldoromal"
   pre: "Mr."
   name: "Lope Doromal Jr."
   affiliation:
    - designation: "Chief Technology Officer"
      company: "IBM Philippines"
   description:
    - "Over his 20 year career in IBM, Lope Doromal Jr. has been in the forefront of the various IT trends that have transformed industries over the years. Starting as an e-business Specialist in the late 90s, when he was the lead advocate for IBM about the value of using this new technology called the Internet for business, to the Analytics-driven Smarter Planet campaign in the late 2000s, when as Chief Technologist, he helped organizations understand how an Instrumented, Interconnected, and Intelligent world changes the way we understand and react to our environment, to his current role as Chief Technology Officer, where is is again leading IBM's campaign around the Cloud and Cognitive technologies."
    - "Concurrently, Lope is also a Client Technical Advisor for the Banking and Financial Markets Industry, providing banking clients with expert, vendor-neutral architectural advice and solution strategies to address the client's strategic business imperatives and current business issues."
   image: "coll_web-speaker-ldoromal.jpg"
 - id: "adumanhug"
   pre: "Mr."
   name: "Allan Jay Dumanhug"
   affiliation:
    - designation: "IT Security Analyst"
      company: "UP IT Development Center"
   description:
    - "Allan is an IT Security Analyst at UP ITDC, Co-Founder and CISO at Secuna, and ICT Coach at STI. At UP ITDC, he works with Software Engineers, System Admins, and Management to ensure IT systems comply with data security & privacy policies, and that IT Systems are protected against malicious attacks. At Secuna, they're on a mission to strengthen the world's capability to build a safer cyberspace. Allan is also a recognized White Hat Hacker. A lot of companies globally acknowledged and rewarded him for helping them finding severe security vulnerabilities. He became a Top Hacker on Facebook for the 1st Quarter of 2016 because of reporting a severe Privilege Escalation on Facebook Pages and hacking 2 websites of Facebook."
   image: "coll_web-speaker-adumanhug.jpg"
 - id: "mlainez"
   pre: "Mr."
   name: "Marc Lainez"
   affiliation:
    - designation: "Systems Engineering Lead, Philippines"
      company: "Palo Alto Networks"
   description:
    - "Marc is the Systems Engineering Lead for Palo Alto Networks in the Philippines. In this role, Marc focuses on providing cybersecurity approaches and educating customers and partners on the Palo Alto Networks Next-Generation Security Platform. In addition, Marc participates in cybersecurity conferences around the Philippines and actively contributes to the cybersecurity communities. Prior to joining Palo Alto Networks, Marc held various positions at Trend Micro including becoming Technical Account Manager supporting the Asia Pacific region; and later, Security Consultant focusing on professional services, consulting, and research. He has more than 10 years of experience in the Cybersecurity industry and holds certifications from ISC2 (Certified Information Systems Security Professional), SANS (GIAC Certified Incident Handler) and VMware (VMware Certified Professional). Marc graduated with a Bachelor of Science in Electronics and Communications Engineering from Rizal Technological University and is currently pursuing a Master’s degree in Technology Management at UP Diliman."
   image: "coll_web-speaker-mlainez.jpg"
 - id: "rregalado"
   pre: "Mr."
   name: "Ralph Vincent Regalado"
   affiliation:
    - designation: "CEO and Founder"
      company: "Senti"
    - designation: "Community Manager"
      company: "Google Developer Group Philippines"
   description:
    - "Ralph is the CEO and Founder of Senti, a localized social media analytics platform. He is also one of the Community Managers of Google Developer Group Philippines. He is an assistant professor, and a Natural Language Processing researcher at De La Salle University, Manila. His research works were presented not only in local but also in international conferences hosted in China, Japan, Vietnam, Indonesia and the United States. When he is not at work, he spends his time travelling and hiking mountains."
   image: "coll_web-speaker-rregalado.jpg"
 - id: "dtapang"
   pre: "Mr."
   name: "David Tapang"
   affiliation:
    - designation: "Education Lead"
      company: "Microsoft Philippines"
   description:
    - "David has been a part of Microsoft Corporation for over 15 years with a majority of that career in the education sector. Having held various leadership roles at Microsoft, he has a deep understanding of education and its importance in global economics. David became the Education Lead for Microsoft Philippines in June of 2013 after returning to Microsoft from a break to pursue other business interests and moving here from the U.S."
   image: "coll_web-speaker-dtapang.jpg"
 - id: "mvalmores"
   pre: "Mr."
   name: "Marco Valmores"
   affiliation:
    - designation: "Team Lead"
      company: "MacAppsLab"
    - designation: "Lead"
      company: "Philippine Android Developers Community"
   description:
    - "Marco is currently leading the Philippine Android Developers Community and started leading it by 4th quarter of 2014. They started doing events in Manila however, towards the third quarter of 2015. By 2016, most of our events have been geared towards helping the provinces learn and enhance Android development. Also leading the initiative of Tech Caravan, they bring Tech Community leaders as well as experts in the provinces in the promise teaching the teachers and students something new. This endeavor was started in the end of 2015 when all the Tech Community leads decided to work together and reach out to the provinces since we have acknowledge there is a great gap to be filled in terms of IT skill sets."
    - "He is currently starting a software company in Zamboanga to help the people get jobs."
    - "He is also currently working with local ICT councils tin organizing Tech Caravan in their provinces."
   image: "coll_web-speaker-mvalmores.jpg"
# - id: "more" # this adds the "And More" panel in the Speakers section

dataSchedules:
 - morning:
    - id: "ldoromal"
      topic: "Harnessing the Power of Watson in Your Applications"
    - id: "dtapang"
      topic: "Innovating with AI"
    - id: "rregalado"
      topic: "Introduction to TensorFlow"
   afternoon:
    - id: "adumanhug"
      topic: "Website Hacking"
    - id: "icanasa"
      topic: "Coding PHP Applications Like a Paranoid"
    - id: "mlainez"
      topic: "Next Generation Cyber Threat Intelligence"
    - id: "mvalmores"
      topic: "Mobile Security"

organizerDescription:
 - "The UP System Information Technology Foundation (UPSITF) Inc. is a non-government organization focused on the application of Information and Communication Technology for development. It partners with UP Information Technology Development Center in providing various services such as, but not limited to, Education Development, IT Human Capital Development, Research &amp; Development, Software Engineering, ICT Policy Development and Planning, and IT Project Management."

dataFAQ:
 - question: "Who can attend the event?"
   answer: "Y4iT Pro is expected to be attended by professionals, and enthusiasts, but of course, everyone is invited to join."
 - question: "How do I register for the event?"
   answer: "To register online, go to pro.y4it.org/register and follow the steps provided. To register on-site, just go to the registration booth, provide the Secretariat with necessary information, and pay for the total registration fee."
 - question: "Can I register online and pay on-site (during event day)?"
   answer: "Yes, you may accomplish the registration form online and pay during event day. However, badge rates depend on the date of purchase and not of registration. Payments made during the event day will follow the walk-in rate."
 - question: "Can I register online and pay offsite (direct payment at UPSITF office or bank deposit) but claim my badge/s on-site?"
   answer: "Yes, you may claim your badge/s on-site or during the event when you register online and pay before the event. Just present the Registration Summary and proof of payment."
 - question: "Why should we register online?"
   answer: "Those who register online will be prioritized during the event. On-site registrants (walk-in participants) will only be accommodated at 9am."
 - question: "I failed to bring or print out my Registration Summary. Would I still be able to claim my badges?"
   answer: "Yes. Just bring proof of payment to claim your badges."
 - question: "I lost my badge, would the management still be able to replace it?"
   answer: "Unfortunately, Y4iT will not replace lost badge/s."
 - question: "How long will the program be?"
   answer: "Gates open at 7am. The program starts at 9am and ends at 4pm."
 - question: "Will there be different programs per day?"
   answer: "Yes, there will be a different program for each day. Expect to learn and be inspired by different speakers and topics each day."
 - question: "I lost my certificate code, would the management still be able to replace it?"
   answer: "Unfortunately, Y4iT will not replace lost certificate codes."

dataPartners:
 - name: "Sponsors"
   id: "sponsor"
   list:
    - name: "Appsfresh"
      logo: "coll_web-partner-sponsor-appsfresh.png"
    - name: "Converge ICT Solutions"
      logo: "coll_web-partner-sponsor-converge.png"
    - name: "Palo Alto Networks"
      logo: "coll_web-partner-sponsor-paloalto.png"
    - name: "Z.com"
      logo: "coll_web-partner-sponsor-zcom.png"
# - name: "Media Partners"
#   id: "media"
#   list:
#    - name: ""
#      logo: ""
# - name: "Organization Partners"
#   list:
#    - name: ""
#      logo: ""

dataTerms:
 - name: "Refunds"
   description: "Tickets are non-refundable but transferrable."
 - name: "Speakers"
   description: "Y4iT reserves the right to cancel or replace speakers."
 - name: "Certificates"
   description: "Lost certificate codes will not be replaced."
